# fly.toml app configuration file generated for ai-portfolio on 2025-06-15T00:30:11+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-portfolio'
primary_region = 'lhr'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
