# fly.toml app configuration file generated for ai-portfolio-morning-glitter-2346 on 2025-06-15T00:27:35+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-portfolio-morning-glitter-2346'
primary_region = 'lhr'

[build]

[env]
  CHAT_RATE_LIMIT = '30/minute'
  EMBEDDING_MODEL = 'text-embedding-3-small'
  FRONTEND_URL = 'https://ai-portfolio.fly.dev'
  GLOBAL_RATE_LIMIT = '1000/hour'
  LLM_MODEL = 'anthropic/claude-3-5-sonnet-latest'
  LLM_ROUTER_URL = 'https://router.requesty.ai/v1'
  POSTGRES_DB = 'postgres'
  POSTGRES_PORT = '5432'
  POSTGRES_SERVER = 'postgresql://pgvector-db.flycast'
  POSTGRES_USER = 'postgres'
  UVICORN_IP = '0.0.0.0'
  UVICORN_PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
