# fly.toml app configuration file generated for ai-portfolio on 2025-06-15T12:12:42+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ai-portfolio"
primary_region = "lhr"

[build]

[env]
LLM_MODEL = "anthropic/claude-3-5-sonnet-latest"
LLM_ROUTER_URL = "https://router.requesty.ai/v1"
UVICORN_IP = "0.0.0.0"
UVICORN_PORT = "8000"
POSTGRES_SERVER = "pgvector-db.flycast"
POSTGRES_PORT = "5432"
POSTGRES_DB = "pgdb"
POSTGRES_USER = "pguser"
FRONTEND_URL = "https://ai-portfolio-mu-seven.vercel.app"
EMBEDDING_MODEL = "text-embedding-3-small"
GLOBAL_RATE_LIMIT = "1000/hour"
CHAT_RATE_LIMIT = "30/minute"
REDIS_URL = "redis://default:a116eb0af9d048a18e4da2f7388d8b02@fly-ai-redis.upstash.io:6379"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 1
processes = ["app"]

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1